### ISSUE TITLE
Request: spoof firmware version 

### ISSUE THREAD

**Issue by orizzle** [mnakada/atomcam_tools#115]
Wyze is trying to force users to update firmware with a popup message when viewing video feed on the app. The popup cannot be closed to view the feed. 
![Screenshot_20240907-232336](https://github.com/user-attachments/assets/d3410316-3bf9-4e2c-af5f-9668bb835f73)

Can a setting be added to spoof the firmware version the server sees, so the popup will not occur?

Excellent work on this project.

**Comment by mnakada** [comment]
Supported in Ver. 2.5.10.
Please write the following in  ``/media/mmc/app.ver``  file and restart.
```
[VER]
appver=4.36.13.0416
```
However, there may be an API inconsistency with the server that may prevent it from working properly.

**Comment by orizzle** [comment]
> Supported in Ver. 2.5.10. Please write the following in `/media/mmc/app.ver` file and restart.
> 
> ```
> [VER]
> appver=4.36.13.0416
> ```
> 
> However, there may be an API inconsistency with the server that may prevent it from working properly.

sorry the pop-up is still persisting with this app.ver file

**Comment by mnakada** [comment]
After writing /media/mmc/app.ver and rebooting, has the /atom/configs/app.ver file changed?
It is the /atom/configs/app.ver that iCamera_app reads on startup.
You can not change /atom/system/bin because it is in the read-only file system.

Click on “upgrade then all at once.” in the app popup, or go to “Update Firmware” in “Account” to check the current version.
(Be careful not to press the UPGRADE button by mistake.)

**Comment by orizzle** [comment]
I was mistaken in my previous post - I was not running the latest version of your tools. This seems to work!
